Page object, Utils, properties, Tests
UladzislauLiashko/SeleniumProject pull request #1
Opened 2023-07-11 16:09 UTC by UladzislauLiashko

page objects, 
utils
tests
properties
models

2023-07-12 14:41 UTC, Fulcrum81 requested changes

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/pages/CartPage.java
> +    public void fillInRequiredInformation(UserInfo userInfo) {
а эти локаторы почему не в проперти файлике?

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/locators/Locators.java
> +    public static By getLocator(String locator, int quantity) {
неплохая идея, правда quantity, пожалуй, не лучшее название для параметра

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/models/DuckOptions.java
> +public class DuckOptions {
Хорошо!

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/models/UserInfo.java
> +public class UserInfo {
Отлично!

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/utils/Utils.java
> +    public void waitForConfirmButtonAvailability() {
Этим двум методам скорее место в страничных классах. Кроме того, по сути, в них содержится ровно то же самое, что и в waitForQuantityChange, просто с конкретным локатором, т.е. можно было бы его и вызвать, просто передав туда локатор

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/utils/Utils.java
> +    public void waitForQuantityChange(By locator) {
Не очень нравится название метода. В сущности он универсальный (какой локатор передашь, того и будетждать), а имя, будто он только с количеством работает

2023-07-12 14:41 UTC, Fulcrum81 commented on src/test/java/Tests/ForThirdHW/CartPageTests.java
> +    private static final By yellowDuck = Locators.getLocator("Catalog.yellowDuck");
Плохо держать локаторы в тестовом классе. Им место на страничках.
Вернее не так, плохо не в принципе в тестовом классе локаторы держать, плохо их держать и в страничных классах и в тестовых.

2023-07-12 14:41 UTC, Fulcrum81 commented on src/test/java/Tests/ForThirdHW/CartPageTests.java
> +        utils.waitForQuantityChange(Locators.getLocator("Catalog.quantityLocator", itemCounter));
вот почему этот метод должен быть универсальным и вызываться со страницы. Тут локатору не место

2023-07-12 14:41 UTC, Fulcrum81 commented on src/main/java/org/example/ThirdSeleniumHW/utils/Utils.java
> +    public Utils(WebDriver driver) {
Вообще я бы статическим этот класс сделал, не беда будет передавать драйвер в сами утильные методы

2023-07-12 14:41 UTC, Fulcrum81 commented on target/classes/org/example/ThirdSeleniumHW/locators/LocatorType.class
Надо бы в gitignore добавить папку target

2023-07-13 07:53 UTC, UladzislauLiashko commented on src/main/java/org/example/ThirdSeleniumHW/utils/Utils.java
> +    public void waitForConfirmButtonAvailability() {
оставли в том же классе, но сделал это одним waiterом

2023-07-13 08:13 UTC, UladzislauLiashko commented on src/test/java/Tests/ForThirdHW/CartPageTests.java
> +        utils.waitForQuantityChange(Locators.getLocator("Catalog.quantityLocator", itemCounter));
я сделал этот метод универсальным, но оставил всё таки в классе утилс - так как он ни к какой конкретной странице не относится. Или как лучше?

2023-07-13 08:44 UTC, UladzislauLiashko commented on src/main/java/org/example/ThirdSeleniumHW/pages/CartPage.java
> +    public void fillInRequiredInformation(UserInfo userInfo) {
перенёс локаторы в проперти файлик

2023-07-13 08:45 UTC, UladzislauLiashko commented on src/main/java/org/example/ThirdSeleniumHW/locators/Locators.java
> +    public static By getLocator(String locator, int quantity) {
поменял название на тоже, что в тесте - itemCounter

2023-07-13 08:45 UTC, UladzislauLiashko commented on src/test/java/Tests/ForThirdHW/CartPageTests.java
> +    private static final By yellowDuck = Locators.getLocator("Catalog.yellowDuck");
перенёс все локаторы из тестов в соответствующие страницы

2023-07-21 06:36 UTC, merged